chore: implement token endpoint url
redhat-developer/rhosak-ui pull request #102
Opened 2023-03-02 08:22 UTC by hemahg

**What this PR does / why we need it**:

> implement token endpoint url

**Which issue(s) this PR fixes** 

> Replace this comment with references to related issues.
> e.g. `fixes #<issue number>`

**Verification steps** 

> Attach a screenshot of the output.
> guidance on how to go the particular story.
> e.g. `point to the story with a text breadcrumb, something like "components > <component name> > <story name>”`

**Is there any work left / what's next** :

> Replace this comment with pending items that need to be covered in this PR or some pending items you are planning to do in the future PR.

**Special notes for your reviewer**:

2023-03-02 11:21 UTC, hemahg commented on apps/consoledot-rhosak/src/routes/control-plane/DrawerProvider.tsx
> +  }, [ssoProviders]);
I have removed useState and useEffect

2023-03-02 11:23 UTC, hemahg commented on packages/consoledot-api/src/queries/useSSOProvider.ts
> +  return useQuery<SsoProviderAllOf>({
I looked into the SDK, But I am not able to find the function that retrieve the data from sdk

2023-03-06 15:38 UTC, riccardo-forina approved these changes
Did you redo an npm install?

2023-03-07 08:21 UTC, hemahg commented on packages/consoledot-api/src/queries/useSSOProvider.ts
> +  if (!tokenEndPointUrl) {
@riccardo-forina, In this line I am trying to check whether the tokenEndPointUrl is present or not and throwing the error, but it's making the application stop running and throw `Token URL is undefined`, could you please assist me with what I am doing wrong here

2023-03-07 11:17 UTC, riccardo-forina requested changes

2023-03-07 11:17 UTC, riccardo-forina commented on packages/consoledot-api/src/queries/useSSOProvider.ts
> +};
```suggestion
export const useSSOTokenEndpoint = () => {
  const { basePath } = useApiConfiguration();

  return useQuery<string>({
    queryKey: masQueries.tokenEndPointUrl(),
    queryFn: async () => {
      const response = await fetch(
        `${basePath}/api/kafkas_mgmt/v1/sso_providers`
      );
      const provider = await response.json();
      const { token_url } = provider;
      if (token_url === undefined || token_url === '') {
        return Promise.reject("Invalid SSO token URL");
      }
      return token_url;
    },
  });
};
```

This is what I meant in my previous comments.

2023-03-07 15:41 UTC, riccardo-forina commented on packages/consoledot-api/src/queries/useSSOProvider.ts
> +      const providers: { token_url?: string } = await response.json();
```suggestion
      const providers = await response.json<{ token_url?: string }>();
```
This should be a bit better, we tell Typescript the shape of the object returned by that json call, so we can do our defensive checks later without having to shut down eslint.

2023-03-07 16:39 UTC, riccardo-forina commented on packages/consoledot-api/src/queries/useSSOProvider.ts
> +      const providers: { token_url?: string } = await response.json();
Ah, yes sure, I was convinced `fetch` could take a type argument

2023-03-07 18:35 UTC, riccardo-forina approved these changes
Looks great but for the thing I commented, I'm not sure that's right

2023-03-07 18:35 UTC, riccardo-forina commented on packages/ui/src/components/KafkaInstanceDrawer/components/KafkaConnectionTabP2.tsx
> +        {isKafkaPending && tokenEndPointUrl ? (
This check doesn't look right?

2023-03-08 08:39 UTC, riccardo-forina approved these changes

2023-03-08 08:39 UTC, riccardo-forina commented on packages/ui/src/components/KafkaInstanceDrawer/components/KafkaConnectionTabP2.tsx
> +        {isKafkaPending || tokenEndPointUrl === undefined ? (
```suggestion
        {tokenEndPointUrl === undefined ? (
```
I don't think we need to wait for the instance to be ready as this url pointed to SSO.

2023-03-08 09:34 UTC, riccardo-forina approved these changes

2023-03-08 09:59 UTC, merged