[WIP] Implement consumer group action items
redhat-developer/rhosak-ui pull request #58
Opened 2023-01-17 11:18 UTC by hemahg

**What this PR does / why we need it:**

- [ ] Integrate consumer group delete modal 
- [ ] Integrate consumer group view partition Drawer
- [ ] Integrate consumer group reset offset modal

2023-01-18 09:09 UTC, riccardo-forina requested changes
The changes are fine, but please:

* re-read the code when you copy-paste it
* use meaningful names for functions and variables. A consumer is something that consumes the data from a topic, a consumer group is a label to describe consumers. Different things.

2023-01-18 09:09 UTC, riccardo-forina commented on packages/consoledot-api/src/mutations/useDeleteConsumerMutation.ts
> +        ]);
There is really no need to invalidate the whole cache for this. We could invalidate the consumer groups related one tho.

2023-01-18 09:09 UTC, riccardo-forina commented on apps/consoledot-rhosak/src/routes/data-plane/routes/ConsumerGroupsRoute.tsx
> +      history.push(`${ControlPlaneRouteRoot}/${instance.id}/details/consumer-groups/${id}/delete`);
We should have a function to generate this string, passed to the component.

2023-01-18 09:09 UTC, riccardo-forina commented on apps/consoledot-rhosak/src/routes/data-plane/useConsumerGate.tsx
> +export function useConsumerGate() {
```suggestion
export function useConsumerGroupGate() {
```

2023-01-18 09:09 UTC, riccardo-forina commented on apps/consoledot-rhosak/src/routes/data-plane/useConsumerGate.tsx
> +    throw Error("useDataPlaneGate used outside the expected route");
```suggestion
    throw Error("useConsumerGroup used outside the expected route");
```

2023-01-18 09:09 UTC, riccardo-forina commented on packages/consoledot-api/src/queries/useConsumerGroup.ts
> +      }
```suggestion
      if (!params.adminUrl) {
        return Promise.reject("Invalid adminUrl");
      }
      if (!params.consumerId) {
        return Promise.reject("Invalid consumerId");
      }
```

2023-01-18 09:09 UTC, riccardo-forina commented on packages/consoledot-api/src/queryKeys.ts
> +      consumer: ({
```suggestion
      consumerGroup: ({
```

2023-01-18 09:09 UTC, riccardo-forina commented on packages/consoledot-api/src/queries/useConsumerGroup.ts
> +    queryKey: kafkaQueries.instance.consumer(params),
```suggestion
    queryKey: kafkaQueries.instance.consumerGroup(params),
```

2023-01-18 09:09 UTC, riccardo-forina commented on packages/consoledot-api/src/transformers/consumerTransformer.ts
> +        groupId: t.groupId || "",
Don't default to empty string. Throw an error if the data we require to be there isn't there.

2023-01-18 09:09 UTC, riccardo-forina commented on packages/consoledot-api/src/transformers/consumerTransformer.ts
> +export function consumerTransformer(t: ConsumerGroupApi): ConsumerGroup {
```suggestion
export function consumerGroupTransformer(t: ConsumerGroupApi): ConsumerGroup {
```

2023-01-20 06:15 UTC, closed without merging

2023-01-20 10:53 UTC, riccardo-forina commented
Did you close this by mistake? The changes were ok as a whole

2023-01-20 10:59 UTC, hemahg commented
I was resolving the merge conflicts not sure how it got closed